import { Product } from './supabase';

export const mockProducts: Product[] = [
  {
    id: '1',
    name: 'Modern Ceramic Vase',
    slug: 'modern-ceramic-vase',
    description: 'A beautiful handcrafted ceramic vase with a minimalist design. Perfect for displaying fresh flowers or as a standalone decorative piece.',
    price: 450,
    category_id: null,
    image_url: '',
    stock: 10,
    featured: true,
    created_at: new Date().toISOString(),
  },
  {
    id: '2',
    name: 'Minimalist Table Lamp',
    slug: 'minimalist-table-lamp',
    description: 'Elegant table lamp with clean lines and warm ambient lighting. Ideal for bedside tables or reading nooks.',
    price: 890,
    category_id: null,
    image_url: '',
    stock: 5,
    featured: true,
    created_at: new Date().toISOString(),
  },
  {
    id: '3',
    name: 'Handwoven Throw Blanket',
    slug: 'handwoven-throw-blanket',
    description: 'Soft, luxurious throw blanket made from premium cotton. Adds warmth and texture to any living space.',
    price: 650,
    category_id: null,
    image_url: '',
    stock: 8,
    featured: true,
    created_at: new Date().toISOString(),
  },
  {
    id: '4',
    name: 'Stone Coaster Set',
    slug: 'stone-coaster-set',
    description: 'Set of 4 natural stone coasters with cork backing. Protects surfaces while adding an organic touch to your home.',
    price: 280,
    category_id: null,
    image_url: '',
    stock: 15,
    featured: true,
    created_at: new Date().toISOString(),
  },
];